### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by webschik** [NativeSH/react-native-iconic-font#1]
Hi! I'm using React Native v0.14.2 for my Android application and I can't use the custom font.

 The font file is located on `MY_APP\android\app\src\main\assets\fonts\MaterialIcons-Regular.ttf`.
And the next code shows broken character instead of icon:

``` js
<Text style={{fontFamily: 'Material Icons', fontSize:30}}>
    //icon 'add'
    {String.fromCharCode(57669)}
</Text>
```

Should I add configuration in Java code or some additional configuration?

**Comment by sospartan** [comment]
'Custom Font' is new feature to Android . It's on master branch but not any release version , yet . 
You may try to compile with the react-native source code from the master branch , or wait for the v0.16 release .
I suggest you wait some time . It's `RC` now , won't take long ...... if everything goes fine.

**Comment by webschik** [comment]
@sospartan, okay, thank you.

**Comment by sospartan** [comment]
@webschik  one more thing , the 'fontFamily' prop should change to 'MaterialIcons' according to the font file name.

**Comment by webschik** [comment]
@sospartan, thanks. I'll try this variant after new release.
