### ISSUE TITLE
Unrecognized font family 'weathericons' Error

### ISSUE THREAD

**Issue by JakeLin** [NativeSH/react-native-iconic-font#6]
Thanks for your project, I have followed the steps in README.md and still geting Unrecognized font family 'weathericons' Error. You can see the demo project on github.com/JakeLin/ReactNativeWeather, the commit SHA is 11cfdd66171e52686ce4ae4ddd5bbef899697ab9

Thanks,
Jake

**Comment by JakeLin** [comment]
Alright, I have fixed this issue by putting the correct font family name, it should be `Weather Icons`. Need to update the document to let the user know about that. Thanks.

**Comment by sospartan** [comment]
:+1:
