### ISSUE TITLE
Whether the font file can be embedded to the js file use base64 or other way?

### ISSUE THREAD

**Issue by bob-chen** [NativeSH/react-native-iconic-font#8]
Hi，

This is a very cool project~ and I want to know do you know some way to embed the font file to the js file? Because in my project it can't add the font file, it cause the package size issue.

I also see the react-native-vector-icons project and others. It seems not be achieved in current..

Thx.

**Comment by sospartan** [comment]
可以的，写个module，加载外部的font文件  https://github.com/facebook/react-native/commit/17fcc9440f9f6f6bbed9c746cb035dd3c4716355
